language: elixir
sudo: false
elixir:
  - 1.7
  - 1.8
  - 1.9
otp_release:
  - 21.3
  - 22.0
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - steve@stevedomin.com
